### ISSUE TITLE
Radix

### ISSUE THREAD

**Issue by AniSkyWorker** [GooseGame/C-oop#3]
- [ ] в функцию ```initWithCheck``` не стоит передавать массив и заполнять его, разбейте данные на несколько переменных
- [ ] при вводе некорректных данных программа не должна падать, она должна выводить сообщение о некорректных данных и завершать выполнение
- [ ] добавить тесты на некорректные данные
- [ ] выпилить комментарии
- [ ] ```makeTenFromOld``` нужно переименовать сокращение десятичной системы счисления - Dec
- [ ] вынести массив, хранящий символы допустимых систем счисления в константу

k = 0.6

**Comment by alexey-malov** [comment]
- [ ] Переименовать initWithCheck в parseCommandLine. Эта функция должна принимать массив ARGV и возвращать уже преобразованные в числа значения.

**Comment by alexey-malov** [comment]
- [ ] Откуда взялась decimal в этой программе?

**Comment by alexey-malov** [comment]
`765 = ((0*10+7)*10+6)*10+5 = (7*10+6)*10+5 = 76*10+5 = 760+5 = 765`
