### ISSUE TITLE
Замечания по Shapes

### ISSUE THREAD

**Issue by alexey-malov** [GooseGame/C-oop#7]
- [x] Починить тесты

**Comment by alexey-malov** [comment]
- [x] Методы геометрических фигур, возвращающие вершины, должны возвращать точки, а не строки

**Comment by alexey-malov** [comment]
- [ ] Реализуйте операцию сравнения точек
https://dev.to/updated_tos/value-objects-in-ruby-13p

**Comment by alexey-malov** [comment]
- [x] Периметра и площади фигуры должны возвращаться с максимальной точностью

**Comment by alexey-malov** [comment]
- [ ] Triangle.getSideOfTriangle не вычисляет длину стороны треугольника, она вичисляет расстояние между точками, поэтому должна называться соотв. образом

**Comment by alexey-malov** [comment]
- [x] Поле @a в Rectangle имеет неудачное имя.

**Comment by alexey-malov** [comment]
- [x] Прекратить "заметать грязь под ковёр" вызывая в случайных местах .to_f.

**Comment by alexey-malov** [comment]
- [ ] Сделать так, чтобы функции поиска фигуры с мин/макс. площадью и периметром требовали O(1) дополнительной памяти.

**Comment by A** [comment]
Полностью согласен! Доколе мы будем и дальше так грязь под ковер заметать? Надо нормально уже сделать!

**Comment by alexey-malov** [comment]
- [ ] Избавиться от warning-ов

**Comment by alexey-malov** [comment]
- [ ] Для рисования фигур должен использоваться метод draw(). В зависимости от наличия у фигуры обводки и заливки должно выполняться рисования контура и закраска внутренностей.

**Comment by alexey-malov** [comment]
- [ ] Метод draw не должен изменять состояние фигуры

**Comment by alexey-malov** [comment]
- [x] Площадь треугольника не должна возвращаться в виде строки для вырожденного треугольника

**Comment by alexey-malov** [comment]
- [x] Периметр треугольника вычисляется неправильно

- [x] Нет адекватных тестов на проверку этой ситуации
